# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,2560x1600@120,0x0,1.3333333
monitor=desc:Shenzhen KTC Technology Group H27V22 0x00000001,preferred,auto,auto
monitor=,preferred,auto,auto

xwayland {
  force_zero_scaling = true
}

###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun -a

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland;xcb


######################
### IMPORT MODULES ###
######################

source = autostart.conf
source = appearance.conf
source = input.conf
source = keybinds.conf
source = win_ws.conf

