##############################
### WINDOWS AND WORKSPACES ###
##############################

# TODO:Default application

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Warn:workaruond for hyprland's bug!!!!!

# float&pin kitty
windowrulev2 = float, initialClass:(.*F.*),initialTitle:^(kitty)$
windowrulev2 = size 70% 70%, initialClass:(.*F.*),initialTitle:^(kitty)$
windowrulev2 = pin , initialClass:(.*G.*),initialTitle:^(kitty)$

# Right-Up of screen
windowrulev2 = size 60% 60% , initialClass:^(RT.*), initialTitle:^(kitty)$
windowrulev2 = float , initialClass:^(RT.*), initialTitle:^(kitty)$
windowrulev2 = move 40% 30 , initialClass:^(RT.*), initialTitle:^(kitty)$

# Thunar Float
windowrulev2 = size 70% 70%, initialClass:^(thunar)$,
windowrulev2 = float , initialClass:^(thunar)$,

# qq pic
windowrulev2 = size 70% 70% , initialClass:^(QQ)$, initialTitle:^(图片查看器)$
windowrulev2 = float , initialClass:^(QQ)$, initialTitle:^(图片查看器)$

# wechat pic & no-border
windowrulev2 = size 70% 70% , initialClass:^(wechat)$, initialTitle:^(预览)$
windowrulev2 = float , initialClass:^(wechat)$, initialTitle:^(预览)$

windowrulev2 = noborder , initialClass:^(wechat)$, 
windowrulev2 = noshadow , initialClass:^(wechat)$, 
windowrulev2 = noblur , initialClass:^(wechat)$, 

# hmcl no border
windowrulev2 = noborder , initialClass:^(org\.jackhuang\.hmcl\.Launcher)$, 
windowrulev2 = noshadow , initialClass:^(org\.jackhuang\.hmcl\.Launcher)$, 
windowrulev2 = noblur , initialClass:^(org\.jackhuang\.hmcl\.Launcher)$, 

# wemeet
windowrulev2 = noborder , initialClass:^(wemeetapp)$, 
windowrulev2 = noshadow , initialClass:^(wemeetapp)$, 
windowrulev2 = noblur , initialClass:^(wemeetapp)$, 
windowrulev2 = pin , initialClass:^(wemeetapp)$, 

# windowrulev2 = workspace 200, class:^(firefox)$
# windowrulev2 = workspace 200, class:^(microsoft-edge)$
# windowrulev2 = workspace 200, class:^(Microsoft-edge)$
# windowrulev2 = workspace 200, class:^(Google-chrome)$

# App adaptations
#

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

## Workspaces
#
workspace = 200, defaultName:󰈹,on-created-empty: [] firefox 
workspace = 201, defaultName:󰨞,on-created-empty: [] code 
workspace = 202, defaultName:󰘅,on-created-empty: [] qq
workspace = 203, defaultName:󰘑,on-created-empty: [] QT_SCALE_FACTOR=1.6 wechat-uos
workspace = 204, defaultName:󱓧,on-created-empty: [] obsidian 

workspace = 1,defaultName: 1,border:0,rounding:0,gapsin:0,gapsout:0, on-created-empty: [] kitty
workspace = 2,defaultName: 2,border:0,rounding:0,gapsin:0,gapsout:0, on-created-empty: [] kitty tmux


