{ config, lib, pkgs, ... }:
let
  gui_path_base = "${config.home.homeDirectory}/nixos-config/modules/gui";
  hyprland_path = "${gui_path_base}/hypr";
  waybar_path = "${gui_path_base}/waybar";
  wofi_path = "${gui_path_base}/wofi";
  wallpaper_path = "${gui_path_base}/wallpaper";
  wpaperd_path = "${gui_path_base}/wpaperd";
  mako_path = "${gui_path_base}/mako";
  custom_cursor = {
    name = "Bibata-Modern-Amber";
    package = pkgs.bibata-cursors;
    size = 32;
  };
in
{
  home.packages = with pkgs; [
    hyprland-qtutils # Hyprland dependence
    #  XDPH is already enabled by programs.hyprland.enable = true;
    # xdg-desktop-portal-hyprland 
    hyprpaper # wallpaper
    wpaperd
    hyprlock # screen-locker
    hyprsunset # warm-color screen (TODO)
    hyprpicker # color picker (TODO)
    hypridle # idle management daemon (TODO screen-lock after wakeup)
    bluetuith # bluetooth tui
    wofi # app launcher
    mako # notification
    hyprpolkitagent # polkit agent (root permission)
    pavucontrol
    networkmanager # tui network
    libnotify # notify-send
    acpi # battery
    brightnessctl
    grim # screenshot
    slurp # screenshot
    libinput-gestures # touchpad gesture
    ydotool
    pinta
    nwg-displays
    kdePackages.kwallet # secret storage(required by zed-editor)
    playerctl
  ];
  # map files
  home.file.".config/hypr".source =
    config.lib.file.mkOutOfStoreSymlink hyprland_path;
  home.file.".config/waybar".source =
    config.lib.file.mkOutOfStoreSymlink waybar_path;
  home.file.".config/wofi".source =
    config.lib.file.mkOutOfStoreSymlink wofi_path;
  home.file.".config/mako".source =
    config.lib.file.mkOutOfStoreSymlink mako_path;
  home.file.".config/wpaperd".source =
    config.lib.file.mkOutOfStoreSymlink wpaperd_path;
  home.file."Pictures/wallpaper/default".source =
    config.lib.file.mkOutOfStoreSymlink wallpaper_path;

  # workaround for plugins 
  # the homemanager's way was against above
  xdg.configFile."hyprnix/default.conf".text = ''
    # Generated by nix, loads plugins only! - Seeker472
    exec = hyprctl plugin load ${pkgs.hyprlandPlugins.hyprexpo}/lib/libhyprexpo.so
    exec = hyprctl setcursor ${custom_cursor.name} ${builtins.toString custom_cursor.size}
  '';

  # set icon-theme
  # if error, use nwg-look manually
  home.pointerCursor = {
    inherit (custom_cursor) name package size;
    gtk.enable = true;
    x11.enable = true;
  };
  gtk = {
    enable = true;
    theme = {
      package = pkgs.kdePackages.breeze-gtk;
      name = "Breeze";
    };
    iconTheme = {
      package = pkgs.kdePackages.breeze-icons;
      name = "breeze";
    };
  };
}
